export interface District {
  id: string;
  name: string;
}

export interface City {
  id: string;
  name: string;
  districts: District[];
}

export const CITIES: City[] = [
  {
    id: '01',
    name: 'Adana',
    districts: [
      { id: '0101', name: 'Aladağ' },
      { id: '0102', name: 'Ceyhan' },
      { id: '0103', name: 'Çukurova' },
      { id: '0104', name: 'Feke' },
      { id: '0105', name: 'İmamoğlu' },
      { id: '0106', name: 'Karaisalı' },
      { id: '0107', name: 'Karataş' },
      { id: '0108', name: 'Kozan' },
      { id: '0109', name: 'Pozantı' },
      { id: '0110', name: 'Saimbeyli' },
      { id: '0111', name: 'Sarıçam' },
      { id: '0112', name: 'Seyhan' },
      { id: '0113', name: 'Tufanbeyli' },
      { id: '0114', name: 'Yumurtalık' },
      { id: '0115', name: 'Yüreğir' },
    ],
  },
  {
    id: '02',
    name: 'Adıyaman',
    districts: [
      { id: '0201', name: 'Besni' },
      { id: '0202', name: 'Çelikhan' },
      { id: '0203', name: 'Gerger' },
      { id: '0204', name: 'Gölbaşı' },
      { id: '0205', name: 'Kâhta' },
      { id: '0206', name: 'Merkez' },
      { id: '0207', name: 'Samsat' },
      { id: '0208', name: 'Sincik' },
      { id: '0209', name: 'Tut' },
    ],
  },
  {
    id: '03',
    name: 'Afyonkarahisar',
    districts: [
      { id: '0301', name: 'Başmakçı' },
      { id: '0302', name: 'Bayat' },
      { id: '0303', name: 'Bolvadin' },
      { id: '0304', name: 'Çay' },
      { id: '0305', name: 'Çobanlar' },
      { id: '0306', name: 'Dazkırı' },
      { id: '0307', name: 'Dinar' },
      { id: '0308', name: 'Emirdağ' },
      { id: '0309', name: 'Evciler' },
      { id: '0310', name: 'Hocalar' },
      { id: '0311', name: 'İhsaniye' },
      { id: '0312', name: 'İscehisar' },
      { id: '0313', name: 'Kızılören' },
      { id: '0314', name: 'Merkez' },
      { id: '0315', name: 'Sandıklı' },
      { id: '0316', name: 'Sinanpaşa' },
      { id: '0317', name: 'Sultandağı' },
      { id: '0318', name: 'Şuhut' },
    ],
  },
  {
    id: '04',
    name: 'Ağrı',
    districts: [
      { id: '0401', name: 'Diyadin' },
      { id: '0402', name: 'Doğubayazıt' },
      { id: '0403', name: 'Eleşkirt' },
      { id: '0404', name: 'Hamur' },
      { id: '0405', name: 'Merkez' },
      { id: '0406', name: 'Patnos' },
      { id: '0407', name: 'Taşlıçay' },
      { id: '0408', name: 'Tutak' },
    ],
  },
  {
    id: '05',
    name: 'Amasya',
    districts: [
      { id: '0501', name: 'Göynücek' },
      { id: '0502', name: 'Gümüşhacıköy' },
      { id: '0503', name: 'Hamamözü' },
      { id: '0504', name: 'Merkez' },
      { id: '0505', name: 'Merzifon' },
      { id: '0506', name: 'Suluova' },
      { id: '0507', name: 'Taşova' },
    ],
  },
  {
    id: '06',
    name: 'Ankara',
    districts: [
      { id: '0601', name: 'Altındağ' },
      { id: '0602', name: 'Akyurt' },
      { id: '0603', name: 'Ayaş' },
      { id: '0604', name: 'Bala' },
      { id: '0605', name: 'Beypazarı' },
      { id: '0606', name: 'Çamlıdere' },
      { id: '0607', name: 'Çankaya' },
      { id: '0608', name: 'Çubuk' },
      { id: '0609', name: 'Elmadağ' },
      { id: '0610', name: 'Etimesgut' },
      { id: '0611', name: 'Evren' },
      { id: '0612', name: 'Gölbaşı' },
      { id: '0613', name: 'Güdül' },
      { id: '0614', name: 'Haymana' },
      { id: '0615', name: 'Kalecik' },
      { id: '0616', name: 'Kazan' },
      { id: '0617', name: 'Keçiören' },
      { id: '0618', name: 'Kızılcahamam' },
      { id: '0619', name: 'Mamak' },
      { id: '0620', name: 'Nallıhan' },
      { id: '0621', name: 'Polatlı' },
      { id: '0622', name: 'Pursaklar' },
      { id: '0623', name: 'Sincan' },
      { id: '0624', name: 'Şereflikoçhisar' },
      { id: '0625', name: 'Yenimahalle' },
    ],
  },
  {
    id: '07',
    name: 'Antalya',
    districts: [
      { id: '0701', name: 'Akseki' },
      { id: '0702', name: 'Aksu' },
      { id: '0703', name: 'Alanya' },
      { id: '0704', name: 'Demre' },
      { id: '0705', name: 'Döşemealtı' },
      { id: '0706', name: 'Elmalı' },
      { id: '0707', name: 'Finike' },
      { id: '0708', name: 'Gazipaşa' },
      { id: '0709', name: 'Gündoğmuş' },
      { id: '0710', name: 'İbradı' },
      { id: '0711', name: 'Kaş' },
      { id: '0712', name: 'Kemer' },
      { id: '0713', name: 'Kepez' },
      { id: '0714', name: 'Konyaaltı' },
      { id: '0715', name: 'Korkuteli' },
      { id: '0716', name: 'Kumluca' },
      { id: '0717', name: 'Manavgat' },
      { id: '0718', name: 'Muratpaşa' },
      { id: '0719', name: 'Serik' },
    ],
  },
  {
    id: '08',
    name: 'Artvin',
    districts: [
      { id: '0801', name: 'Ardanuç' },
      { id: '0802', name: 'Arhavi' },
      { id: '0803', name: 'Borçka' },
      { id: '0804', name: 'Hopa' },
      { id: '0805', name: 'Murgul' },
      { id: '0806', name: 'Merkez' },
      { id: '0807', name: 'Şavşat' },
      { id: '0808', name: 'Yusufeli' },
    ],
  },
  {
    id: '09',
    name: 'Aydın',
    districts: [
      { id: '0901', name: 'Bozdoğan' },
      { id: '0902', name: 'Buharkent' },
      { id: '0903', name: 'Çine' },
      { id: '0904', name: 'Didim' },
      { id: '0905', name: 'Efeler' },
      { id: '0906', name: 'Germencik' },
      { id: '0907', name: 'İncirliova' },
      { id: '0908', name: 'Karacasu' },
      { id: '0909', name: 'Karpuzlu' },
      { id: '0910', name: 'Koçarlı' },
      { id: '0911', name: 'Köşk' },
      { id: '0912', name: 'Kuşadası' },
      { id: '0913', name: 'Kuyucak' },
      { id: '0914', name: 'Nazilli' },
      { id: '0915', name: 'Söke' },
      { id: '0916', name: 'Sultanhisar' },
      { id: '0917', name: 'Yenipazar' },
    ],
  },
  {
    id: '10',
    name: 'Balıkesir',
    districts: [
      { id: '1001', name: 'Altıeylül' },
      { id: '1002', name: 'Ayvalık' },
      { id: '1003', name: 'Balya' },
      { id: '1004', name: 'Bandırma' },
      { id: '1005', name: 'Bigadiç' },
      { id: '1006', name: 'Burhaniye' },
      { id: '1007', name: 'Dursunbey' },
      { id: '1008', name: 'Edremit' },
      { id: '1009', name: 'Erdek' },
      { id: '1010', name: 'Gömeç' },
      { id: '1011', name: 'Gönen' },
      { id: '1012', name: 'Havran' },
      { id: '1013', name: 'İvrindi' },
      { id: '1014', name: 'Karesi' },
      { id: '1015', name: 'Kepsut' },
      { id: '1016', name: 'Manyas' },
      { id: '1017', name: 'Marmara' },
      { id: '1018', name: 'Savaştepe' },
      { id: '1019', name: 'Sındırgı' },
      { id: '1020', name: 'Susurluk' },
    ],
  },
  {
    id: '11',
    name: 'Bilecik',
    districts: [
      { id: '1101', name: 'Bozüyük' },
      { id: '1102', name: 'Gölpazarı' },
      { id: '1103', name: 'İnhisar' },
      { id: '1104', name: 'Merkez' },
      { id: '1105', name: 'Osmaneli' },
      { id: '1106', name: 'Pazaryeri' },
      { id: '1107', name: 'Söğüt' },
      { id: '1108', name: 'Yenipazar' },
    ],
  },
  {
    id: '12',
    name: 'Bingöl',
    districts: [
      { id: '1201', name: 'Adaklı' },
      { id: '1202', name: 'Genç' },
      { id: '1203', name: 'Karlıova' },
      { id: '1204', name: 'Kiğı' },
      { id: '1205', name: 'Merkez' },
      { id: '1206', name: 'Solhan' },
      { id: '1207', name: 'Yayladere' },
      { id: '1208', name: 'Yedisu' },
    ],
  },
  {
    id: '13',
    name: 'Bitlis',
    districts: [
      { id: '1301', name: 'Adilcevaz' },
      { id: '1302', name: 'Ahlat' },
      { id: '1303', name: 'Güroymak' },
      { id: '1304', name: 'Hizan' },
      { id: '1305', name: 'Merkez' },
      { id: '1306', name: 'Mutki' },
      { id: '1307', name: 'Tatvan' },
    ],
  },
  {
    id: '14',
    name: 'Bolu',
    districts: [
      { id: '1401', name: 'Dörtdivan' },
      { id: '1402', name: 'Gerede' },
      { id: '1403', name: 'Göynük' },
      { id: '1404', name: 'Kıbrıscık' },
      { id: '1405', name: 'Mengen' },
      { id: '1406', name: 'Merkez' },
      { id: '1407', name: 'Mudurnu' },
      { id: '1408', name: 'Seben' },
      { id: '1409', name: 'Yeniçağa' },
    ],
  },
  {
    id: '15',
    name: 'Burdur',
    districts: [
      { id: '1501', name: 'Ağlasun' },
      { id: '1502', name: 'Altınyayla' },
      { id: '1503', name: 'Bucak' },
      { id: '1504', name: 'Çavdır' },
      { id: '1505', name: 'Çeltikçi' },
      { id: '1506', name: 'Gölhisar' },
      { id: '1507', name: 'Karamanlı' },
      { id: '1508', name: 'Kemer' },
      { id: '1509', name: 'Merkez' },
      { id: '1510', name: 'Tefenni' },
      { id: '1511', name: 'Yeşilova' },
    ],
  },
  {
    id: '16',
    name: 'Bursa',
    districts: [
      { id: '1601', name: 'Büyükorhan' },
      { id: '1602', name: 'Gemlik' },
      { id: '1603', name: 'Gürsu' },
      { id: '1604', name: 'Harmancık' },
      { id: '1605', name: 'İnegöl' },
      { id: '1606', name: 'İznik' },
      { id: '1607', name: 'Karacabey' },
      { id: '1608', name: 'Keles' },
      { id: '1609', name: 'Kestel' },
      { id: '1610', name: 'Mudanya' },
      { id: '1611', name: 'Mustafakemalpaşa' },
      { id: '1612', name: 'Nilüfer' },
      { id: '1613', name: 'Orhaneli' },
      { id: '1614', name: 'Orhangazi' },
      { id: '1615', name: 'Osmangazi' },
      { id: '1616', name: 'Yenişehir' },
      { id: '1617', name: 'Yıldırım' },
    ],
  },
  {
    id: '17',
    name: 'Çanakkale',
    districts: [
      { id: '1701', name: 'Ayvacık' },
      { id: '1702', name: 'Bayramiç' },
      { id: '1703', name: 'Biga' },
      { id: '1704', name: 'Bozcaada' },
      { id: '1705', name: 'Çan' },
      { id: '1706', name: 'Eceabat' },
      { id: '1707', name: 'Ezine' },
      { id: '1708', name: 'Gelibolu' },
      { id: '1709', name: 'Gökçeada' },
      { id: '1710', name: 'Lapseki' },
      { id: '1711', name: 'Merkez' },
      { id: '1712', name: 'Yenice' },
    ],
  },
  {
    id: '18',
    name: 'Çankırı',
    districts: [
      { id: '1801', name: 'Atkaracalar' },
      { id: '1802', name: 'Bayramören' },
      { id: '1803', name: 'Çerkeş' },
      { id: '1804', name: 'Eldivan' },
      { id: '1805', name: 'Ilgaz' },
      { id: '1806', name: 'Kızılırmak' },
      { id: '1807', name: 'Korgun' },
      { id: '1808', name: 'Kurşunlu' },
      { id: '1809', name: 'Merkez' },
      { id: '1810', name: 'Orta' },
      { id: '1811', name: 'Şabanözü' },
      { id: '1812', name: 'Yapraklı' },
    ],
  },
  {
    id: '19',
    name: 'Çorum',
    districts: [
      { id: '1901', name: 'Alaca' },
      { id: '1902', name: 'Bayat' },
      { id: '1903', name: 'Boğazkale' },
      { id: '1904', name: 'Dodurga' },
      { id: '1905', name: 'İskilip' },
      { id: '1906', name: 'Kargı' },
      { id: '1907', name: 'Laçin' },
      { id: '1908', name: 'Mecitözü' },
      { id: '1909', name: 'Merkez' },
      { id: '1910', name: 'Oğuzlar' },
      { id: '1911', name: 'Ortaköy' },
      { id: '1912', name: 'Osmancık' },
      { id: '1913', name: 'Sungurlu' },
      { id: '1914', name: 'Uğurludağ' },
    ],
  },
  {
    id: '20',
    name: 'Denizli',
    districts: [
      { id: '2001', name: 'Acıpayam' },
      { id: '2002', name: 'Babadağ' },
      { id: '2003', name: 'Baklan' },
      { id: '2004', name: 'Bekilli' },
      { id: '2005', name: 'Beyağaç' },
      { id: '2006', name: 'Bozkurt' },
      { id: '2007', name: 'Buldan' },
      { id: '2008', name: 'Çal' },
      { id: '2009', name: 'Çameli' },
      { id: '2010', name: 'Çardak' },
      { id: '2011', name: 'Çivril' },
      { id: '2012', name: 'Güney' },
      { id: '2013', name: 'Honaz' },
      { id: '2014', name: 'Kale' },
      { id: '2015', name: 'Merkezefendi' },
      { id: '2016', name: 'Pamukkale' },
      { id: '2017', name: 'Sarayköy' },
      { id: '2018', name: 'Serinhisar' },
      { id: '2019', name: 'Tavas' },
    ],
  },
  {
    id: '21',
    name: 'Diyarbakır',
    districts: [
      { id: '2101', name: 'Bağlar' },
      { id: '2102', name: 'Bismil' },
      { id: '2103', name: 'Çermik' },
      { id: '2104', name: 'Çınar' },
      { id: '2105', name: 'Çüngüş' },
      { id: '2106', name: 'Dicle' },
      { id: '2107', name: 'Eğil' },
      { id: '2108', name: 'Ergani' },
      { id: '2109', name: 'Hani' },
      { id: '2110', name: 'Hazro' },
      { id: '2111', name: 'Kayapınar' },
      { id: '2112', name: 'Kocaköy' },
      { id: '2113', name: 'Kulp' },
      { id: '2114', name: 'Lice' },
      { id: '2115', name: 'Silvan' },
      { id: '2116', name: 'Sur' },
      { id: '2117', name: 'Yenişehir' },
    ],
  },
  {
    id: '22',
    name: 'Edirne',
    districts: [
      { id: '2201', name: 'Enez' },
      { id: '2202', name: 'Havsa' },
      { id: '2203', name: 'İpsala' },
      { id: '2204', name: 'Keşan' },
      { id: '2205', name: 'Lalapaşa' },
      { id: '2206', name: 'Meriç' },
      { id: '2207', name: 'Merkez' },
      { id: '2208', name: 'Süloğlu' },
      { id: '2209', name: 'Uzunköprü' },
    ],
  },
  {
    id: '23',
    name: 'Elazığ',
    districts: [
      { id: '2301', name: 'Ağın' },
      { id: '2302', name: 'Alacakaya' },
      { id: '2303', name: 'Arıcak' },
      { id: '2304', name: 'Baskil' },
      { id: '2305', name: 'Karakoçan' },
      { id: '2306', name: 'Keban' },
      { id: '2307', name: 'Kovancılar' },
      { id: '2308', name: 'Maden' },
      { id: '2309', name: 'Merkez' },
      { id: '2310', name: 'Palu' },
      { id: '2311', name: 'Sivrice' },
    ],
  },
  {
    id: '24',
    name: 'Erzincan',
    districts: [
      { id: '2401', name: 'Çayırlı' },
      { id: '2402', name: 'İliç' },
      { id: '2403', name: 'Kemah' },
      { id: '2404', name: 'Kemaliye' },
      { id: '2405', name: 'Merkez' },
      { id: '2406', name: 'Otlukbeli' },
      { id: '2407', name: 'Refahiye' },
      { id: '2408', name: 'Tercan' },
      { id: '2409', name: 'Üzümlü' },
    ],
  },
  {
    id: '25',
    name: 'Erzurum',
    districts: [
      { id: '2501', name: 'Aşkale' },
      { id: '2502', name: 'Aziziye' },
      { id: '2503', name: 'Çat' },
      { id: '2504', name: 'Hınıs' },
      { id: '2505', name: 'Horasan' },
      { id: '2506', name: 'İspir' },
      { id: '2507', name: 'Karaçoban' },
      { id: '2508', name: 'Karayazı' },
      { id: '2509', name: 'Köprüköy' },
      { id: '2510', name: 'Narman' },
      { id: '2511', name: 'Oltu' },
      { id: '2512', name: 'Olur' },
      { id: '2513', name: 'Palandöken' },
      { id: '2514', name: 'Pasinler' },
      { id: '2515', name: 'Pazaryolu' },
      { id: '2516', name: 'Şenkaya' },
      { id: '2517', name: 'Tekman' },
      { id: '2518', name: 'Tortum' },
      { id: '2519', name: 'Uzundere' },
      { id: '2520', name: 'Yakutiye' },
    ],
  },
  {
    id: '26',
    name: 'Eskişehir',
    districts: [
      { id: '2601', name: 'Alpu' },
      { id: '2602', name: 'Beylikova' },
      { id: '2603', name: 'Çifteler' },
      { id: '2604', name: 'Günyüzü' },
      { id: '2605', name: 'Han' },
      { id: '2606', name: 'İnönü' },
      { id: '2607', name: 'Mahmudiye' },
      { id: '2608', name: 'Mihalgazi' },
      { id: '2609', name: 'Mihalıççık' },
      { id: '2610', name: 'Odunpazarı' },
      { id: '2611', name: 'Sarıcakaya' },
      { id: '2612', name: 'Seyitgazi' },
      { id: '2613', name: 'Sivrihisar' },
      { id: '2614', name: 'Tepebaşı' },
    ],
  },
  {
    id: '27',
    name: 'Gaziantep',
    districts: [
      { id: '2701', name: 'Araban' },
      { id: '2702', name: 'İslahiye' },
      { id: '2703', name: 'Karkamış' },
      { id: '2704', name: 'Nizip' },
      { id: '2705', name: 'Nurdağı' },
      { id: '2706', name: 'Oğuzeli' },
      { id: '2707', name: 'Şahinbey' },
      { id: '2708', name: 'Şehitkamil' },
      { id: '2709', name: 'Yavuzeli' },
    ],
  },
  {
    id: '28',
    name: 'Giresun',
    districts: [
      { id: '2801', name: 'Alucra' },
      { id: '2802', name: 'Bulancak' },
      { id: '2803', name: 'Çamoluk' },
      { id: '2804', name: 'Çanakçı' },
      { id: '2805', name: 'Dereli' },
      { id: '2806', name: 'Doğankent' },
      { id: '2807', name: 'Espiye' },
      { id: '2808', name: 'Eynesil' },
      { id: '2809', name: 'Görele' },
      { id: '2810', name: 'Güce' },
      { id: '2811', name: 'Keşap' },
      { id: '2812', name: 'Merkez' },
      { id: '2813', name: 'Piraziz' },
      { id: '2814', name: 'Şebinkarahisar' },
      { id: '2815', name: 'Tirebolu' },
      { id: '2816', name: 'Yağlıdere' },
    ],
  },
  {
    id: '29',
    name: 'Gümüşhane',
    districts: [
      { id: '2901', name: 'Merkez' },
      { id: '2902', name: 'Kelkit' },
      { id: '2903', name: 'Köse' },
      { id: '2904', name: 'Kürtün' },
      { id: '2905', name: 'Şiran' },
      { id: '2906', name: 'Torul' },
    ],
  },
  {
    id: '30',
    name: 'Hakkâri',
    districts: [
      { id: '3001', name: 'Çukurca' },
      { id: '3002', name: 'Derecik' },
      { id: '3003', name: 'Merkez' },
      { id: '3004', name: 'Şemdinli' },
      { id: '3005', name: 'Yüksekova' },
    ],
  },
  {
    id: '31',
    name: 'Hatay',
    districts: [
      { id: '3101', name: 'Altınözü' },
      { id: '3102', name: 'Antakya' },
      { id: '3103', name: 'Arsuz' },
      { id: '3104', name: 'Belen' },
      { id: '3105', name: 'Defne' },
      { id: '3106', name: 'Dörtyol' },
      { id: '3107', name: 'Erzin' },
      { id: '3108', name: 'Hassa' },
      { id: '3109', name: 'İskenderun' },
      { id: '3110', name: 'Kırıkhan' },
      { id: '3111', name: 'Kumlu' },
      { id: '3112', name: 'Payas' },
      { id: '3113', name: 'Reyhanlı' },
      { id: '3114', name: 'Samandağ' },
      { id: '3115', name: 'Yayladağı' },
    ],
  },
  {
    id: '32',
    name: 'Isparta',
    districts: [
      { id: '3201', name: 'Aksu' },
      { id: '3202', name: 'Atabey' },
      { id: '3203', name: 'Eğirdir' },
      { id: '3204', name: 'Gelendost' },
      { id: '3205', name: 'Gönen' },
      { id: '3206', name: 'Keçiborlu' },
      { id: '3207', name: 'Merkez' },
      { id: '3208', name: 'Senirkent' },
      { id: '3209', name: 'Sütçüler' },
      { id: '3210', name: 'Şarkikaraağaç' },
      { id: '3211', name: 'Uluborlu' },
      { id: '3212', name: 'Yalvaç' },
      { id: '3213', name: 'Yenişarbademli' },
    ],
  },
  {
    id: '33',
    name: 'Mersin',
    districts: [
      { id: '3301', name: 'Akdeniz' },
      { id: '3302', name: 'Anamur' },
      { id: '3303', name: 'Aydıncık' },
      { id: '3304', name: 'Bozyazı' },
      { id: '3305', name: 'Çamlıyayla' },
      { id: '3306', name: 'Erdemli' },
      { id: '3307', name: 'Gülnar' },
      { id: '3308', name: 'Mezitli' },
      { id: '3309', name: 'Mut' },
      { id: '3310', name: 'Silifke' },
      { id: '3311', name: 'Tarsus' },
      { id: '3312', name: 'Toroslar' },
      { id: '3313', name: 'Yenişehir' },
    ],
  },
  {
    id: '34',
    name: 'İstanbul',
    districts: [
      { id: '3401', name: 'Adalar' },
      { id: '3402', name: 'Arnavutköy' },
      { id: '3403', name: 'Ataşehir' },
      { id: '3404', name: 'Avcılar' },
      { id: '3405', name: 'Bağcılar' },
      { id: '3406', name: 'Bahçelievler' },
      { id: '3407', name: 'Bakırköy' },
      { id: '3408', name: 'Başakşehir' },
      { id: '3409', name: 'Bayrampaşa' },
      { id: '3410', name: 'Beşiktaş' },
      { id: '3411', name: 'Beykoz' },
      { id: '3412', name: 'Beylikdüzü' },
      { id: '3413', name: 'Beyoğlu' },
      { id: '3414', name: 'Büyükçekmece' },
      { id: '3415', name: 'Çatalca' },
      { id: '3416', name: 'Çekmeköy' },
      { id: '3417', name: 'Esenler' },
      { id: '3418', name: 'Esenyurt' },
      { id: '3419', name: 'Eyüpsultan' },
      { id: '3420', name: 'Fatih' },
      { id: '3421', name: 'Gaziosmanpaşa' },
      { id: '3422', name: 'Güngören' },
      { id: '3423', name: 'Kadıköy' },
      { id: '3424', name: 'Kağıthane' },
      { id: '3425', name: 'Kartal' },
      { id: '3426', name: 'Küçükçekmece' },
      { id: '3427', name: 'Maltepe' },
      { id: '3428', name: 'Pendik' },
      { id: '3429', name: 'Sancaktepe' },
      { id: '3430', name: 'Sarıyer' },
      { id: '3431', name: 'Silivri' },
      { id: '3432', name: 'Sultanbeyli' },
      { id: '3433', name: 'Sultangazi' },
      { id: '3434', name: 'Şile' },
      { id: '3435', name: 'Şişli' },
      { id: '3436', name: 'Tuzla' },
      { id: '3437', name: 'Ümraniye' },
      { id: '3438', name: 'Üsküdar' },
      { id: '3439', name: 'Zeytinburnu' },
    ],
  },
  {
    id: '35',
    name: 'İzmir',
    districts: [
      { id: '3501', name: 'Aliağa' },
      { id: '3502', name: 'Balçova' },
      { id: '3503', name: 'Bayındır' },
      { id: '3504', name: 'Bayraklı' },
      { id: '3505', name: 'Bergama' },
      { id: '3506', name: 'Beydağ' },
      { id: '3507', name: 'Bornova' },
      { id: '3508', name: 'Buca' },
      { id: '3509', name: 'Çeşme' },
      { id: '3510', name: 'Çiğli' },
      { id: '3511', name: 'Dikili' },
      { id: '3512', name: 'Foça' },
      { id: '3513', name: 'Gaziemir' },
      { id: '3514', name: 'Güzelbahçe' },
      { id: '3515', name: 'Karabağlar' },
      { id: '3516', name: 'Karaburun' },
      { id: '3517', name: 'Karşıyaka' },
      { id: '3518', name: 'Kemalpaşa' },
      { id: '3519', name: 'Kınık' },
      { id: '3520', name: 'Kiraz' },
      { id: '3521', name: 'Konak' },
      { id: '3522', name: 'Menderes' },
      { id: '3523', name: 'Menemen' },
      { id: '3524', name: 'Narlıdere' },
      { id: '3525', name: 'Ödemiş' },
      { id: '3526', name: 'Seferihisar' },
      { id: '3527', name: 'Selçuk' },
      { id: '3528', name: 'Tire' },
      { id: '3529', name: 'Torbalı' },
      { id: '3530', name: 'Urla' },
    ],
  },
  {
    id: '36',
    name: 'Kars',
    districts: [
      { id: '3601', name: 'Akyaka' },
      { id: '3602', name: 'Arpaçay' },
      { id: '3603', name: 'Digor' },
      { id: '3604', name: 'Kağızman' },
      { id: '3605', name: 'Merkez' },
      { id: '3606', name: 'Sarıkamış' },
      { id: '3607', name: 'Selim' },
      { id: '3608', name: 'Susz' },
    ],
  },
  {
    id: '37',
    name: 'Kastamonu',
    districts: [
      { id: '3701', name: 'Abana' },
      { id: '3702', name: 'Ağlı' },
      { id: '3703', name: 'Araç' },
      { id: '3704', name: 'Azdavay' },
      { id: '3705', name: 'Bozkurt' },
      { id: '3706', name: 'Cide' },
      { id: '3707', name: 'Çatalzeytin' },
      { id: '3708', name: 'Daday' },
      { id: '3709', name: 'Devrekani' },
      { id: '3710', name: 'Doğanyurt' },
      { id: '3711', name: 'Hanönü' },
      { id: '3712', name: 'İhsangazi' },
      { id: '3713', name: 'İnebolu' },
      { id: '3714', name: 'Küre' },
      { id: '3715', name: 'Merkez' },
      { id: '3716', name: 'Pınarbaşı' },
      { id: '3717', name: 'Seydiler' },
      { id: '3718', name: 'Şenpazar' },
      { id: '3719', name: 'Taşköprü' },
      { id: '3720', name: 'Tosya' },
    ],
  },
  {
    id: '38',
    name: 'Kayseri',
    districts: [
      { id: '3801', name: 'Akkışla' },
      { id: '3802', name: 'Bünyan' },
      { id: '3803', name: 'Develi' },
      { id: '3804', name: 'Felahiye' },
      { id: '3805', name: 'Hacılar' },
      { id: '3806', name: 'İncesu' },
      { id: '3807', name: 'Kocasinan' },
      { id: '3808', name: 'Melikgazi' },
      { id: '3809', name: 'Özvatan' },
      { id: '3810', name: 'Pınarbaşı' },
      { id: '3811', name: 'Sarıoğlan' },
      { id: '3812', name: 'Sarız' },
      { id: '3813', name: 'Talas' },
      { id: '3814', name: 'Tomarza' },
      { id: '3815', name: 'Yahyalı' },
      { id: '3816', name: 'Yeşilhisar' },
    ],
  },
  {
    id: '39',
    name: 'Kırklareli',
    districts: [
      { id: '3901', name: 'Babaeski' },
      { id: '3902', name: 'Demirköy' },
      { id: '3903', name: 'Kofçaz' },
      { id: '3904', name: 'Lüleburgaz' },
      { id: '3905', name: 'Merkez' },
      { id: '3906', name: 'Pehlivanköy' },
      { id: '3907', name: 'Pınarhisar' },
      { id: '3908', name: 'Vize' },
    ],
  },
  {
    id: '40',
    name: 'Kırşehir',
    districts: [
      { id: '4001', name: 'Akçakent' },
      { id: '4002', name: 'Akpınar' },
      { id: '4003', name: 'Boztepe' },
      { id: '4004', name: 'Çiçekdağı' },
      { id: '4005', name: 'Kaman' },
      { id: '4006', name: 'Merkez' },
      { id: '4007', name: 'Mucur' },
    ],
  },
  {
    id: '41',
    name: 'Kocaeli',
    districts: [
      { id: '4101', name: 'Başiskele' },
      { id: '4102', name: 'Çayırova' },
      { id: '4103', name: 'Darıca' },
      { id: '4104', name: 'Derince' },
      { id: '4105', name: 'Dilovası' },
      { id: '4106', name: 'Gebze' },
      { id: '4107', name: 'Gölcük' },
      { id: '4108', name: 'İzmit' },
      { id: '4109', name: 'Kandıra' },
      { id: '4110', name: 'Karamürsel' },
      { id: '4111', name: 'Kartepe' },
      { id: '4112', name: 'Körfez' },
    ],
  },
  {
    id: '42',
    name: 'Konya',
    districts: [
      { id: '4201', name: 'Ahırlı' },
      { id: '4202', name: 'Akören' },
      { id: '4203', name: 'Akşehir' },
      { id: '4204', name: 'Altınekin' },
      { id: '4205', name: 'Beyşehir' },
      { id: '4206', name: 'Bozkır' },
      { id: '4207', name: 'Cihanbeyli' },
      { id: '4208', name: 'Çeltik' },
      { id: '4209', name: 'Çumra' },
      { id: '4210', name: 'Derbent' },
      { id: '4211', name: 'Derebucak' },
      { id: '4212', name: 'Doğanhisar' },
      { id: '4213', name: 'Emirgazi' },
      { id: '4214', name: 'Ereğli' },
      { id: '4215', name: 'Güneysınır' },
      { id: '4216', name: 'Hadim' },
      { id: '4217', name: 'Halkapınar' },
      { id: '4218', name: 'Hüyük' },
      { id: '4219', name: 'Ilgın' },
      { id: '4220', name: 'Kadınhanı' },
      { id: '4221', name: 'Karapınar' },
      { id: '4222', name: 'Karatay' },
      { id: '4223', name: 'Kulu' },
      { id: '4224', name: 'Meram' },
      { id: '4225', name: 'Sarayönü' },
      { id: '4226', name: 'Selçuklu' },
      { id: '4227', name: 'Seydişehir' },
      { id: '4228', name: 'Taşkent' },
      { id: '4229', name: 'Tuzlukçu' },
      { id: '4230', name: 'Yalıhüyük' },
      { id: '4231', name: 'Yunak' },
    ],
  },
  {
    id: '43',
    name: 'Kütahya',
    districts: [
      { id: '4301', name: 'Altıntaş' },
      { id: '4302', name: 'Aslanapa' },
      { id: '4303', name: 'Çavdarhisar' },
      { id: '4304', name: 'Domaniç' },
      { id: '4305', name: 'Dumlupınar' },
      { id: '4306', name: 'Emet' },
      { id: '4307', name: 'Gediz' },
      { id: '4308', name: 'Hisarcık' },
      { id: '4309', name: 'Merkez' },
      { id: '4310', name: 'Pazarlar' },
      { id: '4311', name: 'Simav' },
      { id: '4312', name: 'Şaphane' },
      { id: '4313', name: 'Tavşanlı' },
    ],
  },
  {
    id: '44',
    name: 'Malatya',
    districts: [
      { id: '4401', name: 'Akçadağ' },
      { id: '4402', name: 'Arapgir' },
      { id: '4403', name: 'Arguvan' },
      { id: '4404', name: 'Battalgazi' },
      { id: '4405', name: 'Darende' },
      { id: '4406', name: 'Doğanşehir' },
      { id: '4407', name: 'Doğanyol' },
      { id: '4408', name: 'Hekimhan' },
      { id: '4409', name: 'Kale' },
      { id: '4410', name: 'Kuluncak' },
      { id: '4411', name: 'Pütürge' },
      { id: '4412', name: 'Yazıhan' },
      { id: '4413', name: 'Yeşilyurt' },
    ],
  },
  {
    id: '45',
    name: 'Manisa',
    districts: [
      { id: '4501', name: 'Ahmetli' },
      { id: '4502', name: 'Akhisar' },
      { id: '4503', name: 'Alaşehir' },
      { id: '4504', name: 'Demirci' },
      { id: '4505', name: 'Gölmarmara' },
      { id: '4506', name: 'Gördes' },
      { id: '4507', name: 'Kırkağaç' },
      { id: '4508', name: 'Köprübaşı' },
      { id: '4509', name: 'Kula' },
      { id: '4510', name: 'Salihli' },
      { id: '4511', name: 'Sarıgöl' },
      { id: '4512', name: 'Saruhanlı' },
      { id: '4513', name: 'Selendi' },
      { id: '4514', name: 'Soma' },
      { id: '4515', name: 'Şehzadeler' },
      { id: '4516', name: 'Turgutlu' },
      { id: '4517', name: 'Yunusemre' },
    ],
  },
  {
    id: '46',
    name: 'Kahramanmaraş',
    districts: [
      { id: '4601', name: 'Afşin' },
      { id: '4602', name: 'Andırın' },
      { id: '4603', name: 'Çağlayancerit' },
      { id: '4604', name: 'Dulkadiroğlu' },
      { id: '4605', name: 'Ekinözü' },
      { id: '4606', name: 'Elbistan' },
      { id: '4607', name: 'Göksun' },
      { id: '4608', name: 'Nurhak' },
      { id: '4609', name: 'Onikişubat' },
      { id: '4610', name: 'Pazarcık' },
      { id: '4611', name: 'Türkoğlu' },
    ],
  },
  {
    id: '47',
    name: 'Mardin',
    districts: [
      { id: '4701', name: 'Artuklu' },
      { id: '4702', name: 'Dargeçit' },
      { id: '4703', name: 'Derik' },
      { id: '4704', name: 'Kızıltepe' },
      { id: '4705', name: 'Mazıdağı' },
      { id: '4706', name: 'Midyat' },
      { id: '4707', name: 'Nusaybin' },
      { id: '4708', name: 'Ömerli' },
      { id: '4709', name: 'Savur' },
      { id: '4710', name: 'Yeşilli' },
    ],
  },
  {
    id: '48',
    name: 'Muğla',
    districts: [
      { id: '4801', name: 'Bodrum' },
      { id: '4802', name: 'Dalaman' },
      { id: '4803', name: 'Datça' },
      { id: '4804', name: 'Fethiye' },
      { id: '4805', name: 'Kavaklıdere' },
      { id: '4806', name: 'Köyceğiz' },
      { id: '4807', name: 'Marmaris' },
      { id: '4808', name: 'Menteşe' },
      { id: '4809', name: 'Milas' },
      { id: '4810', name: 'Ortaca' },
      { id: '4811', name: 'Seydikemer' },
      { id: '4812', name: 'Ula' },
      { id: '4813', name: 'Yatağan' },
    ],
  },
  {
    id: '49',
    name: 'Muş',
    districts: [
      { id: '4901', name: 'Bulanık' },
      { id: '4902', name: 'Hasköy' },
      { id: '4903', name: 'Korkut' },
      { id: '4904', name: 'Malazgirt' },
      { id: '4905', name: 'Merkez' },
      { id: '4906', name: 'Varto' },
    ],
  },
  {
    id: '50',
    name: 'Nevşehir',
    districts: [
      { id: '5001', name: 'Acıgöl' },
      { id: '5002', name: 'Avanos' },
      { id: '5003', name: 'Derinkuyu' },
      { id: '5004', name: 'Gülşehir' },
      { id: '5005', name: 'Hacıbektaş' },
      { id: '5006', name: 'Kozaklı' },
      { id: '5007', name: 'Merkez' },
      { id: '5008', name: 'Ürgüp' },
    ],
  },
  {
    id: '51',
    name: 'Niğde',
    districts: [
      { id: '5101', name: 'Altunhisar' },
      { id: '5102', name: 'Bor' },
      { id: '5103', name: 'Çamardı' },
      { id: '5104', name: 'Çiftlik' },
      { id: '5105', name: 'Merkez' },
      { id: '5106', name: 'Ulukışla' },
    ],
  },
  {
    id: '52',
    name: 'Ordu',
    districts: [
      { id: '5201', name: 'Akkuş' },
      { id: '5202', name: 'Altınordu' },
      { id: '5203', name: 'Aybastı' },
      { id: '5204', name: 'Çamaş' },
      { id: '5205', name: 'Çatalpınar' },
      { id: '5206', name: 'Çaybaşı' },
      { id: '5207', name: 'Fatsa' },
      { id: '5208', name: 'Gölköy' },
      { id: '5209', name: 'Gülyalı' },
      { id: '5210', name: 'Gürgentepe' },
      { id: '5211', name: 'İkizce' },
      { id: '5212', name: 'Kabadüz' },
      { id: '5213', name: 'Kabataş' },
      { id: '5214', name: 'Korgan' },
      { id: '5215', name: 'Kumru' },
      { id: '5216', name: 'Mesudiye' },
      { id: '5217', name: 'Perşembe' },
      { id: '5218', name: 'Ulubey' },
      { id: '5219', name: 'Ünye' },
    ],
  },
  {
    id: '53',
    name: 'Rize',
    districts: [
      { id: '5301', name: 'Ardeşen' },
      { id: '5302', name: 'Çamlıhemşin' },
      { id: '5303', name: 'Çayeli' },
      { id: '5304', name: 'Derepazarı' },
      { id: '5305', name: 'Fındıklı' },
      { id: '5306', name: 'Güneysu' },
      { id: '5307', name: 'Hemşin' },
      { id: '5308', name: 'İkizdere' },
      { id: '5309', name: 'İyidere' },
      { id: '5310', name: 'Kalkandere' },
      { id: '5311', name: 'Merkez' },
      { id: '5312', name: 'Pazar' },
    ],
  },
  {
    id: '54',
    name: 'Sakarya',
    districts: [
      { id: '5401', name: 'Adapazarı' },
      { id: '5402', name: 'Akyazı' },
      { id: '5403', name: 'Arifiye' },
      { id: '5404', name: 'Erenler' },
      { id: '5405', name: 'Ferizli' },
      { id: '5406', name: 'Geyve' },
      { id: '5407', name: 'Hendek' },
      { id: '5408', name: 'Karapürçek' },
      { id: '5409', name: 'Karasu' },
      { id: '5410', name: 'Kaynarca' },
      { id: '5411', name: 'Kocaali' },
      { id: '5412', name: 'Pamukova' },
      { id: '5413', name: 'Sapanca' },
      { id: '5414', name: 'Serdivan' },
      { id: '5415', name: 'Söğütlü' },
      { id: '5416', name: 'Taraklı' },
    ],
  },
  {
    id: '55',
    name: 'Samsun',
    districts: [
      { id: '5501', name: 'Alaçam' },
      { id: '5502', name: 'Asarcık' },
      { id: '5503', name: 'Atakum' },
      { id: '5504', name: 'Ayvacık' },
      { id: '5505', name: 'Bafra' },
      { id: '5506', name: 'Canik' },
      { id: '5507', name: 'Çarşamba' },
      { id: '5508', name: 'Havza' },
      { id: '5509', name: 'İlkadım' },
      { id: '5510', name: 'Kavak' },
      { id: '5511', name: 'Ladik' },
      { id: '5512', name: 'Ondokuzmayıs' },
      { id: '5513', name: 'Salıpazarı' },
      { id: '5514', name: 'Tekkeköy' },
      { id: '5515', name: 'Terme' },
      { id: '5516', name: 'Vezirköprü' },
      { id: '5517', name: 'Yakakent' },
    ],
  },
  {
    id: '56',
    name: 'Siirt',
    districts: [
      { id: '5601', name: 'Baykan' },
      { id: '5602', name: 'Eruh' },
      { id: '5603', name: 'Kurtalan' },
      { id: '5604', name: 'Merkez' },
      { id: '5605', name: 'Pervari' },
      { id: '5606', name: 'Şirvan' },
      { id: '5607', name: 'Tillo' },
    ],
  },
  {
    id: '57',
    name: 'Sinop',
    districts: [
      { id: '5701', name: 'Ayancık' },
      { id: '5702', name: 'Boyabat' },
      { id: '5703', name: 'Dikmen' },
      { id: '5704', name: 'Durağan' },
      { id: '5705', name: 'Erfelek' },
      { id: '5706', name: 'Gerze' },
      { id: '5707', name: 'Merkez' },
      { id: '5708', name: 'Saraydüzü' },
      { id: '5709', name: 'Türkeli' },
    ],
  },
  {
    id: '58',
    name: 'Sivas',
    districts: [
      { id: '5801', name: 'Akıncılar' },
      { id: '5802', name: 'Altınyayla' },
      { id: '5803', name: 'Divriği' },
      { id: '5804', name: 'Doğanşar' },
      { id: '5805', name: 'Gemerek' },
      { id: '5806', name: 'Gölova' },
      { id: '5807', name: 'Gürün' },
      { id: '5808', name: 'Hafik' },
      { id: '5809', name: 'İmranlı' },
      { id: '5810', name: 'Kangal' },
      { id: '5811', name: 'Koyulhisar' },
      { id: '5812', name: 'Merkez' },
      { id: '5813', name: 'Suşehri' },
      { id: '5814', name: 'Şarkışla' },
      { id: '5815', name: 'Ulaş' },
      { id: '5816', name: 'Yıldızeli' },
      { id: '5817', name: 'Zara' },
    ],
  },
  {
    id: '59',
    name: 'Tekirdağ',
    districts: [
      { id: '5901', name: 'Çerkezköy' },
      { id: '5902', name: 'Çorlu' },
      { id: '5903', name: 'Ergene' },
      { id: '5904', name: 'Hayrabolu' },
      { id: '5905', name: 'Kapaklı' },
      { id: '5906', name: 'Malkara' },
      { id: '5907', name: 'Marmara Ereğlisi' },
      { id: '5908', name: 'Muratlı' },
      { id: '5909', name: 'Saray' },
      { id: '5910', name: 'Süleymanpaşa' },
      { id: '5911', name: 'Şarköy' },
    ],
  },
  {
    id: '60',
    name: 'Tokat',
    districts: [
      { id: '6001', name: 'Almus' },
      { id: '6002', name: 'Artova' },
      { id: '6003', name: 'Başçiftlik' },
      { id: '6004', name: 'Erbaa' },
      { id: '6005', name: 'Merkez' },
      { id: '6006', name: 'Niksar' },
      { id: '6007', name: 'Pazar' },
      { id: '6008', name: 'Reşadiye' },
      { id: '6009', name: 'Sulusaray' },
      { id: '6010', name: 'Turhal' },
      { id: '6011', name: 'Yeşilyurt' },
      { id: '6012', name: 'Zile' },
    ],
  },
  {
    id: '61',
    name: 'Trabzon',
    districts: [
      { id: '6101', name: 'Akçaabat' },
      { id: '6102', name: 'Araklı' },
      { id: '6103', name: 'Arsin' },
      { id: '6104', name: 'Beşikdüzü' },
      { id: '6105', name: 'Çarşıbaşı' },
      { id: '6106', name: 'Çaykara' },
      { id: '6107', name: 'Dernekpazarı' },
      { id: '6108', name: 'Düzköy' },
      { id: '6109', name: 'Hayrat' },
      { id: '6110', name: 'Köprübaşı' },
      { id: '6111', name: 'Maçka' },
      { id: '6112', name: 'Of' },
      { id: '6113', name: 'Ortahisar' },
      { id: '6114', name: 'Sürmene' },
      { id: '6115', name: 'Şalpazarı' },
      { id: '6116', name: 'Tonya' },
      { id: '6117', name: 'Vakfıkebir' },
      { id: '6118', name: 'Yomra' },
    ],
  },
  {
    id: '62',
    name: 'Tunceli',
    districts: [
      { id: '6201', name: 'Çemişgezek' },
      { id: '6202', name: 'Hozat' },
      { id: '6203', name: 'Mazgirt' },
      { id: '6204', name: 'Merkez' },
      { id: '6205', name: 'Nazımiye' },
      { id: '6206', name: 'Ovacık' },
      { id: '6207', name: 'Pertek' },
      { id: '6208', name: 'Pülümür' },
    ],
  },
  {
    id: '63',
    name: 'Şanlıurfa',
    districts: [
      { id: '6301', name: 'Akçakale' },
      { id: '6302', name: 'Birecik' },
      { id: '6303', name: 'Bozova' },
      { id: '6304', name: 'Ceylanpınar' },
      { id: '6305', name: 'Eyyübiye' },
      { id: '6306', name: 'Halfeti' },
      { id: '6307', name: 'Haliliye' },
      { id: '6308', name: 'Harran' },
      { id: '6309', name: 'Hilvan' },
      { id: '6310', name: 'Karaköprü' },
      { id: '6311', name: 'Siverek' },
      { id: '6312', name: 'Suruç' },
      { id: '6313', name: 'Viranşehir' },
    ],
  },
  {
    id: '64',
    name: 'Uşak',
    districts: [
      { id: '6401', name: 'Banaz' },
      { id: '6402', name: 'Eşme' },
      { id: '6403', name: 'Karahallı' },
      { id: '6404', name: 'Merkez' },
      { id: '6405', name: 'Sivaslı' },
      { id: '6406', name: 'Ulubey' },
    ],
  },
  {
    id: '65',
    name: 'Van',
    districts: [
      { id: '6501', name: 'Bahçesaray' },
      { id: '6502', name: 'Başkale' },
      { id: '6503', name: 'Çaldıran' },
      { id: '6504', name: 'Çatak' },
      { id: '6505', name: 'Edremit' },
      { id: '6506', name: 'Erciş' },
      { id: '6507', name: 'Gevaş' },
      { id: '6508', name: 'Gürpınar' },
      { id: '6509', name: 'İpekyolu' },
      { id: '6510', name: 'Muradiye' },
      { id: '6511', name: 'Özalp' },
      { id: '6512', name: 'Saray' },
      { id: '6513', name: 'Tuşba' },
    ],
  },
  {
    id: '66',
    name: 'Yozgat',
    districts: [
      { id: '6601', name: 'Akdağmadeni' },
      { id: '6602', name: 'Aydıncık' },
      { id: '6603', name: 'Boğazlıyan' },
      { id: '6604', name: 'Çandır' },
      { id: '6605', name: 'Çayıralan' },
      { id: '6606', name: 'Çekerek' },
      { id: '6607', name: 'Kadışehri' },
      { id: '6608', name: 'Merkez' },
      { id: '6609', name: 'Saraykent' },
      { id: '6610', name: 'Sarıkaya' },
      { id: '6611', name: 'Sorgun' },
      { id: '6612', name: 'Şefaatli' },
      { id: '6613', name: 'Yenifakılı' },
      { id: '6614', name: 'Yerköy' },
    ],
  },
  {
    id: '67',
    name: 'Zonguldak',
    districts: [
      { id: '6701', name: 'Alaplı' },
      { id: '6702', name: 'Çaycuma' },
      { id: '6703', name: 'Devrek' },
      { id: '6704', name: 'Ereğli' },
      { id: '6705', name: 'Gökçebey' },
      { id: '6706', name: 'Kilimli' },
      { id: '6707', name: 'Kozlu' },
      { id: '6708', name: 'Merkez' },
    ],
  },
  {
    id: '68',
    name: 'Aksaray',
    districts: [
      { id: '6801', name: 'Ağaçören' },
      { id: '6802', name: 'Eskil' },
      { id: '6803', name: 'Gülağaç' },
      { id: '6804', name: 'Güzelyurt' },
      { id: '6805', name: 'Merkez' },
      { id: '6806', name: 'Ortaköy' },
      { id: '6807', name: 'Sarıyahşi' },
      { id: '6808', name: 'Sultanhanı' },
    ],
  },
  {
    id: '69',
    name: 'Bayburt',
    districts: [
      { id: '6901', name: 'Aydıntepe' },
      { id: '6902', name: 'Demirözü' },
      { id: '6903', name: 'Merkez' },
    ],
  },
  {
    id: '70',
    name: 'Karaman',
    districts: [
      { id: '7001', name: 'Ayrancı' },
      { id: '7002', name: 'Başyayla' },
      { id: '7003', name: 'Ermenek' },
      { id: '7004', name: 'Kazımkarabekir' },
      { id: '7005', name: 'Merkez' },
      { id: '7006', name: 'Sarıveliler' },
    ],
  },
  {
    id: '71',
    name: 'Kırıkkale',
    districts: [
      { id: '7101', name: 'Bahşılı' },
      { id: '7102', name: 'Balışeyh' },
      { id: '7103', name: 'Çelebi' },
      { id: '7104', name: 'Delice' },
      { id: '7105', name: 'Karakeçili' },
      { id: '7106', name: 'Keskin' },
      { id: '7107', name: 'Merkez' },
      { id: '7108', name: 'Sulakyurt' },
      { id: '7109', name: 'Yahşihan' },
    ],
  },
  {
    id: '72',
    name: 'Batman',
    districts: [
      { id: '7201', name: 'Beşiri' },
      { id: '7202', name: 'Gercüş' },
      { id: '7203', name: 'Hasankeyf' },
      { id: '7204', name: 'Kozluk' },
      { id: '7205', name: 'Merkez' },
      { id: '7206', name: 'Sason' },
    ],
  },
  {
    id: '73',
    name: 'Şırnak',
    districts: [
      { id: '7301', name: 'Beytüşşebap' },
      { id: '7302', name: 'Cizre' },
      { id: '7303', name: 'Güçlükonak' },
      { id: '7304', name: 'İdil' },
      { id: '7305', name: 'Merkez' },
      { id: '7306', name: 'Silopi' },
      { id: '7307', name: 'Uludere' },
    ],
  },
  {
    id: '74',
    name: 'Bartın',
    districts: [
      { id: '7401', name: 'Amasra' },
      { id: '7402', name: 'Kurucaşile' },
      { id: '7403', name: 'Merkez' },
      { id: '7404', name: 'Ulus' },
    ],
  },
  {
    id: '75',
    name: 'Ardahan',
    districts: [
      { id: '7501', name: 'Çıldır' },
      { id: '7502', name: 'Damal' },
      { id: '7503', name: 'Göle' },
      { id: '7504', name: 'Hanak' },
      { id: '7505', name: 'Merkez' },
      { id: '7506', name: 'Posof' },
    ],
  },
  {
    id: '76',
    name: 'Iğdır',
    districts: [
      { id: '7601', name: 'Aralık' },
      { id: '7602', name: 'Karakoyunlu' },
      { id: '7603', name: 'Merkez' },
      { id: '7604', name: 'Tuzluca' },
    ],
  },
  {
    id: '77',
    name: 'Yalova',
    districts: [
      { id: '7701', name: 'Altınova' },
      { id: '7702', name: 'Armutlu' },
      { id: '7703', name: 'Çınarcık' },
      { id: '7704', name: 'Çiftlikköy' },
      { id: '7705', name: 'Merkez' },
      { id: '7706', name: 'Termal' },
    ],
  },
  {
    id: '78',
    name: 'Karabük',
    districts: [
      { id: '7801', name: 'Eflani' },
      { id: '7802', name: 'Eskipazar' },
      { id: '7803', name: 'Merkez' },
      { id: '7804', name: 'Ovacık' },
      { id: '7805', name: 'Safranbolu' },
      { id: '7806', name: 'Yenice' },
    ],
  },
  {
    id: '79',
    name: 'Kilis',
    districts: [
      { id: '7901', name: 'Elbeyli' },
      { id: '7902', name: 'Merkez' },
      { id: '7903', name: 'Musabeyli' },
      { id: '7904', name: 'Polateli' },
    ],
  },
  {
    id: '80',
    name: 'Osmaniye',
    districts: [
      { id: '8001', name: 'Bahçe' },
      { id: '8002', name: 'Düziçi' },
      { id: '8003', name: 'Hasanbeyli' },
      { id: '8004', name: 'Kadirli' },
      { id: '8005', name: 'Merkez' },
      { id: '8006', name: 'Sumbas' },
      { id: '8007', name: 'Toprakkale' },
    ],
  },
  {
    id: '81',
    name: 'Düzce',
    districts: [
      { id: '8101', name: 'Akçakoca' },
      { id: '8102', name: 'Cumayeri' },
      { id: '8103', name: 'Çilimli' },
      { id: '8104', name: 'Gölyaka' },
      { id: '8105', name: 'Gümüşova' },
      { id: '8106', name: 'Kaynaşlı' },
      { id: '8107', name: 'Merkez' },
      { id: '8108', name: 'Yığılca' },
    ],
  },
];

// Merkez ilçeler (her ilin merkez ilçesinin adı)
const CENTRAL_DISTRICTS: Record<string, string> = {
  '01': 'Seyhan', '02': 'Merkez', '03': 'Merkez', '04': 'Merkez', '05': 'Merkez',
  '06': 'Çankaya', '07': 'Muratpaşa', '08': 'Merkez', '09': 'Efeler', '10': 'Merkez',
  '11': 'Merkez', '12': 'Merkez', '13': 'Merkez', '14': 'Merkez', '15': 'Merkez',
  '16': 'Osmangazi', '17': 'Merkez', '18': 'Merkez', '19': 'Merkez', '20': 'Merkez',
  '21': 'Bağlar', '22': 'Merkez', '23': 'Merkez', '24': 'Merkez', '25': 'Yakutiye',
  '26': 'Odunpazarı', '27': 'Şahinbey', '28': 'Merkez', '29': 'Merkez', '30': 'Merkez',
  '31': 'Antakya', '32': 'Merkez', '33': 'Mezitli', '34': 'Kadıköy', '35': 'Bornova',
  '36': 'Merkez', '37': 'Merkez', '38': 'Melikgazi', '39': 'Merkez', '40': 'Merkez',
  '41': 'İzmit', '42': 'Selçuklu', '43': 'Merkez', '44': 'Yeşilyurt', '45': 'Yunusemre',
  '46': 'Dulkadiroğlu', '47': 'Artuklu', '48': 'Menteşe', '49': 'Merkez', '50': 'Merkez',
  '51': 'Merkez', '52': 'Altınordu', '53': 'Ardeşen', '54': 'Adapazarı', '55': 'Atakum',
  '56': 'Merkez', '57': 'Merkez', '58': 'Merkez', '59': 'Merkez', '60': 'Merkez',
  '61': 'Ortahisar', '62': 'Merkez', '63': 'Haliliye', '64': 'Merkez', '65': 'İpekyolu',
  '66': 'Merkez', '67': 'Merkez', '68': 'Merkez', '69': 'Merkez', '70': 'Merkez',
  '71': 'Merkez', '72': 'Merkez', '73': 'Merkez', '74': 'Merkez', '75': 'Merkez',
  '76': 'Merkez', '77': 'Merkez', '78': 'Merkez', '79': 'Merkez', '80': 'Merkez',
  '81': 'Merkez',
};

export function getDistricts(cityId: string): District[] {
  const city = CITIES.find((c) => c.id === cityId);
  if (!city) return [];
  const centralName = CENTRAL_DISTRICTS[cityId];
  if (!centralName) return city.districts;
  // Merkez ilçeyi en üste taşı
  const central = city.districts.find(d => d.name === centralName);
  const others = city.districts.filter(d => d.name !== centralName);
  return central ? [central, ...others] : city.districts;
}

export function getCityName(cityId: string): string {
  const city = CITIES.find((c) => c.id === cityId);
  return city?.name ?? '';
}
