export type RootStackParamList = {
  Login: undefined;
  MainTabs: undefined;
  LoadCreate: undefined;
  LoadTracking: undefined;
  LoadTrackingDetail: { loadId: string };
  LoadAcceptDetail: { loadId: string };
  MyBids: undefined;
  CarrierProfile: undefined;
  ReturnLoad: { deliveryLat: number; deliveryLng: number };
  InvoiceList: undefined;
  InvoiceCreate: undefined;
  InvoiceDetail: { invoiceId: string };
  AccountantDashboard: undefined;
  TaxDashboard: undefined;
  WebhookManagement: undefined;
  ApiKeyManagement: undefined;
  AnalyticsDashboard: undefined;
  AdminPanel: undefined;
  FuelStations: undefined;
  Restaurants: undefined;
  RoutePlanner: undefined;
  ChatList: undefined;
  ChatCreate: undefined;
  ChatRoom: { roomId: string };
  DeliveryProof: undefined;
  TruckNavigation: {
    loadId: string;
    originLat: number;
    originLng: number;
    destLat: number;
    destLng: number;
    fromCity: string;
    toCity: string;
  };
  DriveMode: undefined;
  DriverDashboard: undefined;
  DocumentCenter: undefined;
  DuyuruYonetim: undefined;
  AiDialog: undefined;
  Finance: undefined;
  Kitchen: undefined;
  MyVehicles: undefined;
  VehicleForm: { vehicle?: string; editMode: boolean; missingFields?: string[] };
  VehicleSale: { vehicle: string };
  ListingDetail: { listingId: string };
  ListingsBrowse: undefined;
  CategoryBrowse: undefined;
  Wallet: undefined;
  SavedCards: undefined;
  Subscription: undefined;
  BillingHistory: undefined;
  CreditShop: undefined;
  CommissionConfig: undefined;
  PlanManagement: undefined;
  CreditPackageMgmt: undefined;
  PartMarketHome: undefined;
  PartMarketSearch: { query?: string; category?: string; categoryName?: string };
  PartListingDetail: { id: string };
  PartListingCreate: undefined;
  MyPartListings: undefined;
  PartOffers: undefined;
  PartTransaction: { listingId: string };
  PartDispute: { transactionId: string };
  PartReviews: { userId: string; userName?: string };
};

export type TabParamList = {
  Home: undefined;
  LoadCreateTab: undefined;
  FAB: undefined;
  LoadAccept: undefined;
  Profile: undefined;
};

export type HomeStackParamList = {
  HomeScreen: undefined;
  FuelStations: undefined;
  Restaurants: undefined;
};

export type FinanceStackParamList = {
  FinanceDashboard: undefined;
  ExpensesList: undefined;
  AddExpense: undefined;
};

export type ProfileStackParamList = {
  ProfileMain: undefined;
  CarrierProfile: undefined;
  Wallet: undefined;
  Subscription: undefined;
  SavedCards: undefined;
  BillingHistory: undefined;
  CreditShop: undefined;
  PartMarketHome: undefined;
  PartMarketSearch: { query?: string; category?: string; categoryName?: string };
  PartListingDetail: { id: string };
  PartListingCreate: undefined;
  MyPartListings: undefined;
  MyVehicles: undefined;
  ChatList: undefined;
  InvoiceList: undefined;
  LoadTracking: undefined;
  MyBids: undefined;
  FuelStations: undefined;
  Restaurants: undefined;
  AnalyticsDashboard: undefined;
  AdminPanel: undefined;
  InvoiceCreate: undefined;
  AccountantDashboard: undefined;
  TaxDashboard: undefined;
  WebhookManagement: undefined;
  ApiKeyManagement: undefined;
  DuyuruYonetim: undefined;
  Kitchen: undefined;
  AiDialog: undefined;
  Finance: undefined;
  LoadTrackingDetail: { loadId: string };
  LoadAcceptDetail: { loadId: string };
  CommissionConfig: undefined;
  PlanManagement: undefined;
  CreditPackageMgmt: undefined;
};
